package ch.rasc.jrefine.tools.declarations;

import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.ast.expr.CastExpr;
import com.github.javaparser.ast.expr.EnclosedExpr;
import com.github.javaparser.ast.expr.InstanceOfExpr;
import com.github.javaparser.ast.expr.LambdaExpr;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.ThisExpr;
import com.github.javaparser.ast.stmt.IfStmt;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import com.github.javaparser.ast.type.Type;
import ch.rasc.jrefine.analysis.AstSupport;
import ch.rasc.jrefine.analysis.TypeLookup;
import ch.rasc.jrefine.api.Finding;
import ch.rasc.jrefine.api.InspectionContext;
import ch.rasc.jrefine.api.PolicyInspectionTool;
import ch.rasc.jrefine.api.ToolResult;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Reports source-local declarations that depend on stronger abstractions than their API
 * needs.
 */
public final class ReportAbstractionDesignIssuesTool implements PolicyInspectionTool {

	private static final Set<String> OPTIONAL_TYPES = Set.of("Optional", "OptionalDouble", "OptionalInt",
			"OptionalLong");

	private static final Set<String> CONCRETE_COLLECTION_TYPES = Set.of("ArrayDeque", "ArrayList", "HashMap", "HashSet",
			"Hashtable", "IdentityHashMap", "LinkedHashMap", "LinkedHashSet", "LinkedList", "PriorityQueue", "Stack",
			"TreeMap", "TreeSet", "Vector", "WeakHashMap");

	@Override
	public String id() {
		return "report-abstraction-design-issues";
	}

	@Override
	public String description() {
		return "Report source-local abstraction, cast, collection, and API/interface design issues";
	}

	@Override
	public ToolResult inspect(InspectionContext context, boolean applyFixes) {
		if (generatedSource(context)) {
			return new ToolResult(List.of(), false);
		}
		ArrayList<Finding> findings = new ArrayList<>();
		optionalMembers(context, findings);
		booleanParameters(context, findings);
		instanceofDesign(context, findings);
		overlyStrongCasts(context, findings);
		concreteCollections(context, findings);
		interfaceDrift(context, findings);
		subclassReferences(context, findings);
		objectMethodInterfaces(context, findings);
		privateMethodsUsedByInnerClass(context, findings);
		return new ToolResult(List.copyOf(findings), false);
	}

	private static void optionalMembers(InspectionContext context, List<Finding> findings) {
		context.compilationUnit()
			.findAll(FieldDeclaration.class)
			.stream()
			.flatMap(field -> field.getVariables().stream())
			.filter(variable -> knownOptional(context, variable.getType()))
			.forEach(variable -> findings.add(Finding.at(variable, "Optional is used as a field type")));
		context.compilationUnit()
			.findAll(Parameter.class)
			.stream()
			.filter(parameter -> !(parameter.getParentNode().orElse(null) instanceof LambdaExpr))
			.filter(parameter -> knownOptional(context, parameter.getType()))
			.forEach(parameter -> findings
				.add(Finding.at(parameter, "Optional is used as a method or constructor parameter type")));
	}

	private static boolean knownOptional(InspectionContext context, Type type) {
		return TypeLookup.isKnownJavaUtilType(context.compilationUnit(), type.asString(), OPTIONAL_TYPES);
	}

	private static void booleanParameters(InspectionContext context, List<Finding> findings) {
		context.compilationUnit()
			.findAll(MethodDeclaration.class)
			.stream()
			.filter(MethodDeclaration::isPublic)
			.filter(method -> method.getAnnotationByName("Override").isEmpty()
					&& method.getAnnotationByName("java.lang.Override").isEmpty())
			.flatMap(method -> method.getParameters().stream())
			.filter(parameter -> parameter.getAnnotations().isEmpty())
			.filter(parameter -> parameter.getType().isPrimitiveType() && parameter.getType()
				.asPrimitiveType()
				.getType() == com.github.javaparser.ast.type.PrimitiveType.Primitive.BOOLEAN)
			.forEach(parameter -> findings.add(Finding.at(parameter,
					"Public method uses a boolean parameter instead of a descriptive operation")));
	}

	private static boolean generatedSource(InspectionContext context) {
		String source = context.editor().source();
		String prefix = source.substring(0, Math.min(source.length(), 1_000)).toLowerCase(java.util.Locale.ROOT);
		return prefix.contains("generated by") || context.compilationUnit()
			.getTypes()
			.stream()
			.flatMap(type -> type.getAnnotations().stream())
			.anyMatch(annotation -> annotation.getName().getIdentifier().equals("Generated")
					|| annotation.getName().getIdentifier().equals("SuppressWarnings")
							&& annotation.toString().contains("\"all\""));
	}

	private static void instanceofDesign(InspectionContext context, List<Finding> findings) {
		for (InstanceOfExpr expression : context.compilationUnit().findAll(InstanceOfExpr.class)) {
			if (expression.getExpression() instanceof ThisExpr) {
				findings.add(Finding.at(expression,
						"'this' is tested with instanceof; polymorphism may express the intent"));
			}
		}
		for (IfStmt statement : context.compilationUnit().findAll(IfStmt.class)) {
			if (statement.getParentNode()
				.filter(IfStmt.class::isInstance)
				.map(IfStmt.class::cast)
				.filter(parent -> parent.getElseStmt().orElse(null) == statement)
				.isPresent()) {
				continue;
			}
			ArrayList<InstanceOfExpr> tests = new ArrayList<>();
			IfStmt current = statement;
			int branches = 1;
			while (true) {
				tests.addAll(current.getCondition().findAll(InstanceOfExpr.class));
				if (!(current.getElseStmt().orElse(null) instanceof IfStmt next)) {
					break;
				}
				current = next;
				branches++;
			}
			Map<String, Long> subjects = tests.stream()
				.collect(java.util.stream.Collectors.groupingBy(test -> test.getExpression().toString(),
						java.util.stream.Collectors.counting()));
			if (branches >= 2 && subjects.values().stream().anyMatch(count -> count >= 2)) {
				findings.add(Finding.at(statement,
						"Chain of instanceof checks on the same value may need polymorphic dispatch"));
			}
		}
	}

	private static void overlyStrongCasts(InspectionContext context, List<Finding> findings) {
		Map<String, ClassOrInterfaceDeclaration> types = uniqueTypes(context);
		for (CastExpr cast : context.compilationUnit().findAll(CastExpr.class)) {
			if (!cast.getType().isClassOrInterfaceType() || !unqualified(cast.getType().asString())) {
				continue;
			}
			ClassOrInterfaceDeclaration target = types.get(simpleType(cast.getType().asString()));
			MethodCallExpr call = receiverCall(cast);
			if (target == null || call == null || !call.getArguments().isEmpty()
					|| target.getMethodsByName(call.getNameAsString())
						.stream()
						.anyMatch(method -> method.getParameters().isEmpty())) {
				continue;
			}
			String weaker = uniqueWeakerReceiver(target, call.getNameAsString(), types);
			if (weaker != null) {
				findings.add(Finding.at(cast, "Cast to " + target.getNameAsString() + " is stronger than required; "
						+ weaker + " provides the invoked operation"));
			}
		}
	}

	private static MethodCallExpr receiverCall(CastExpr cast) {
		Node receiver = cast;
		while (receiver.getParentNode().orElse(null) instanceof EnclosedExpr enclosed
				&& enclosed.getInner() == receiver) {
			receiver = enclosed;
		}
		if (receiver.getParentNode().orElse(null) instanceof MethodCallExpr call
				&& call.getScope().orElse(null) == receiver) {
			return call;
		}
		return null;
	}

	private static String uniqueWeakerReceiver(ClassOrInterfaceDeclaration target, String methodName,
			Map<String, ClassOrInterfaceDeclaration> types) {
		List<ClassOrInterfaceDeclaration> frontier = directSourceParents(target, types);
		Set<String> visited = new HashSet<>();
		while (!frontier.isEmpty()) {
			List<ClassOrInterfaceDeclaration> candidates = frontier.stream()
				.filter(type -> providesZeroArgumentMethod(type, methodName, types, new HashSet<>()))
				.toList();
			if (candidates.size() == 1) {
				return candidates.getFirst().getNameAsString();
			}
			if (candidates.size() > 1) {
				return null;
			}
			ArrayList<ClassOrInterfaceDeclaration> next = new ArrayList<>();
			frontier.stream()
				.filter(type -> visited.add(type.getNameAsString()))
				.forEach(type -> next.addAll(directSourceParents(type, types)));
			frontier = next;
		}
		return null;
	}

	private static boolean providesZeroArgumentMethod(ClassOrInterfaceDeclaration type, String methodName,
			Map<String, ClassOrInterfaceDeclaration> types, Set<String> visited) {
		if (!visited.add(type.getNameAsString())) {
			return false;
		}
		if (type.getMethodsByName(methodName)
			.stream()
			.anyMatch(method -> method.getParameters().isEmpty() && !method.isPrivate() && !method.isStatic())) {
			return true;
		}
		return directSourceParents(type, types).stream()
			.anyMatch(parent -> providesZeroArgumentMethod(parent, methodName, types, visited));
	}

	private static List<ClassOrInterfaceDeclaration> directSourceParents(ClassOrInterfaceDeclaration type,
			Map<String, ClassOrInterfaceDeclaration> types) {
		ArrayList<ClassOrInterfaceType> references = new ArrayList<>(type.getExtendedTypes());
		references.addAll(type.getImplementedTypes());
		return references.stream()
			.filter(reference -> unqualified(reference.asString()))
			.map(reference -> types.get(simpleType(reference.asString())))
			.filter(java.util.Objects::nonNull)
			.toList();
	}

	private static void concreteCollections(InspectionContext context, List<Finding> findings) {
		context.compilationUnit()
			.findAll(VariableDeclarator.class)
			.stream()
			.filter(variable -> AstSupport.ancestor(variable, FieldDeclaration.class).isPresent())
			.filter(variable -> knownConcreteCollection(context, variable.getType()))
			.forEach(variable -> findings.add(Finding.at(variable, "Collection is declared by concrete class "
					+ simpleType(variable.getType().asString()) + " instead of an interface")));
		context.compilationUnit()
			.findAll(Parameter.class)
			.stream()
			.filter(parameter -> !(parameter.getParentNode().orElse(null) instanceof LambdaExpr))
			.filter(parameter -> knownConcreteCollection(context, parameter.getType()))
			.forEach(parameter -> findings
				.add(Finding.at(parameter, "Collection parameter is declared by concrete class "
						+ simpleType(parameter.getType().asString()))));
		context.compilationUnit()
			.findAll(MethodDeclaration.class)
			.stream()
			.filter(method -> knownConcreteCollection(context, method.getType()))
			.forEach(method -> findings
				.add(Finding.at(method.getType(), "Collection return type is declared by concrete class "
						+ simpleType(method.getType().asString()))));
	}

	private static boolean knownConcreteCollection(InspectionContext context, Type type) {
		return TypeLookup.isKnownJavaUtilType(context.compilationUnit(), type.asString(), CONCRETE_COLLECTION_TYPES);
	}

	private static void interfaceDrift(InspectionContext context, List<Finding> findings) {
		Map<String, ClassOrInterfaceDeclaration> types = uniqueTypes(context);
		for (ClassOrInterfaceDeclaration type : context.compilationUnit().findAll(ClassOrInterfaceDeclaration.class)) {
			if (type.isInterface() || types.get(type.getNameAsString()) != type) {
				continue;
			}
			Set<ClassOrInterfaceDeclaration> interfaces = interfaceClosure(type, types, new HashSet<>());
			if (interfaces.isEmpty()) {
				continue;
			}
			List<MethodDeclaration> contracts = interfaces.stream()
				.flatMap(parent -> parent.getMethods().stream())
				.toList();
			type.getMethods()
				.stream()
				.filter(MethodDeclaration::isPublic)
				.filter(method -> !method.isStatic() && !objectMethod(context, method))
				.filter(method -> contracts.stream().noneMatch(contract -> sameSignature(method, contract)))
				.forEach(method -> findings
					.add(Finding.at(method, "Public method is not exposed through an implemented interface")));
		}
	}

	private static Set<ClassOrInterfaceDeclaration> interfaceClosure(ClassOrInterfaceDeclaration type,
			Map<String, ClassOrInterfaceDeclaration> types, Set<String> visited) {
		LinkedHashSet<ClassOrInterfaceDeclaration> result = new LinkedHashSet<>();
		ArrayList<ClassOrInterfaceType> parents = new ArrayList<>(type.getImplementedTypes());
		parents.addAll(type.getExtendedTypes());
		for (ClassOrInterfaceType reference : parents) {
			if (!unqualified(reference.asString())) {
				continue;
			}
			String name = simpleType(reference.asString());
			if (!visited.add(name)) {
				continue;
			}
			ClassOrInterfaceDeclaration parent = types.get(name);
			if (parent == null) {
				continue;
			}
			if (parent.isInterface()) {
				result.add(parent);
			}
			result.addAll(interfaceClosure(parent, types, visited));
		}
		return result;
	}

	private static void subclassReferences(InspectionContext context, List<Finding> findings) {
		Map<String, ClassOrInterfaceDeclaration> types = uniqueTypes(context);
		Map<String, Set<String>> subclasses = new HashMap<>();
		for (ClassOrInterfaceDeclaration candidate : types.values()) {
			for (ClassOrInterfaceType parent : candidate.getExtendedTypes()) {
				if (unqualified(parent.asString()) && types.containsKey(simpleType(parent.asString()))) {
					subclasses.computeIfAbsent(simpleType(parent.asString()), ignored -> new HashSet<>())
						.add(candidate.getNameAsString());
				}
			}
		}
		for (ClassOrInterfaceDeclaration type : context.compilationUnit().findAll(ClassOrInterfaceDeclaration.class)) {
			Set<String> children = subclasses.getOrDefault(type.getNameAsString(), Set.of());
			if (children.isEmpty()) {
				continue;
			}
			ClassOrInterfaceType reference = type.findAll(ClassOrInterfaceType.class)
				.stream()
				.filter(candidate -> AstSupport.ancestor(candidate, TypeDeclaration.class)
					.filter(owner -> owner == type)
					.isPresent())
				.filter(candidate -> children.contains(simpleType(candidate.asString())))
				.filter(candidate -> !type.getPermittedTypes().contains(candidate))
				.findFirst()
				.orElse(null);
			if (reference != null) {
				findings.add(Finding.at(reference,
						"Class references its source-local subclass '" + simpleType(reference.asString()) + "'"));
			}
		}
	}

	private static void objectMethodInterfaces(InspectionContext context, List<Finding> findings) {
		for (ClassOrInterfaceDeclaration type : context.compilationUnit().findAll(ClassOrInterfaceDeclaration.class)) {
			if (!type.isInterface()) {
				continue;
			}
			type.getMethods()
				.stream()
				.filter(method -> objectMethod(context, method))
				.forEach(method -> findings
					.add(Finding.at(method, "Interface method clashes with a method declared by Object")));
		}
	}

	private static boolean objectMethod(InspectionContext context, MethodDeclaration method) {
		return switch (method.getNameAsString()) {
			case "equals" ->
				method.getParameters().size() == 1 && TypeLookup.isKnownJavaLangType(context.compilationUnit(),
						method.getParameter(0).getType().asString(), Set.of("Object"));
			case "hashCode", "toString", "getClass", "clone", "finalize", "notify", "notifyAll" ->
				method.getParameters().isEmpty();
			case "wait" -> method.getParameters().isEmpty()
					|| method.getParameters().size() == 1 && "long".equals(method.getParameter(0).getType().asString())
					|| method.getParameters().size() == 2 && "long".equals(method.getParameter(0).getType().asString())
							&& "int".equals(method.getParameter(1).getType().asString());
			default -> false;
		};
	}

	private static void privateMethodsUsedByInnerClass(InspectionContext context, List<Finding> findings) {
		for (ClassOrInterfaceDeclaration owner : context.compilationUnit().findAll(ClassOrInterfaceDeclaration.class)) {
			for (MethodDeclaration method : owner.getMethods().stream().filter(MethodDeclaration::isPrivate).toList()) {
				List<MethodCallExpr> calls = owner.findAll(MethodCallExpr.class)
					.stream()
					.filter(call -> call.getNameAsString().equals(method.getNameAsString())
							&& call.getArguments().size() == method.getParameters().size())
					.filter(call -> !method.isAncestorOf(call))
					.toList();
				boolean usedByOwner = calls.stream()
					.anyMatch(call -> AstSupport.ancestor(call, TypeDeclaration.class)
						.filter(type -> type == owner)
						.isPresent());
				boolean usedByInner = calls.stream().anyMatch(call -> {
					TypeDeclaration<?> inner = AstSupport.ancestor(call, TypeDeclaration.class).orElse(null);
					if (inner == null || inner == owner || !owner.isAncestorOf(inner)) {
						return false;
					}
					if (call.getScope().isPresent()
							&& !call.getScope().orElseThrow().toString().equals(owner.getNameAsString() + ".this")) {
						return false;
					}
					return !(inner instanceof ClassOrInterfaceDeclaration declaration) || declaration
						.getMethodsByName(call.getNameAsString())
						.stream()
						.noneMatch(innerMethod -> innerMethod.getParameters().size() == call.getArguments().size());
				});
				if (!usedByOwner && usedByInner) {
					findings.add(Finding.at(method, "Private method is used only from an inner class"));
				}
			}
		}
	}

	private static boolean sameSignature(MethodDeclaration left, MethodDeclaration right) {
		if (!left.getNameAsString().equals(right.getNameAsString())
				|| left.getParameters().size() != right.getParameters().size()) {
			return false;
		}
		for (int index = 0; index < left.getParameters().size(); index++) {
			String leftType = normalizeType(left.getParameter(index).getType().asString())
					+ (left.getParameter(index).isVarArgs() ? "[]" : "");
			String rightType = normalizeType(right.getParameter(index).getType().asString())
					+ (right.getParameter(index).isVarArgs() ? "[]" : "");
			if (!leftType.equals(rightType)) {
				return false;
			}
		}
		return true;
	}

	private static Map<String, ClassOrInterfaceDeclaration> uniqueTypes(InspectionContext context) {
		HashMap<String, List<ClassOrInterfaceDeclaration>> grouped = new HashMap<>();
		context.compilationUnit()
			.findAll(ClassOrInterfaceDeclaration.class)
			.forEach(type -> grouped.computeIfAbsent(type.getNameAsString(), ignored -> new ArrayList<>()).add(type));
		HashMap<String, ClassOrInterfaceDeclaration> result = new HashMap<>();
		grouped.forEach((name, declarations) -> {
			if (declarations.size() == 1) {
				result.put(name, declarations.getFirst());
			}
		});
		return result;
	}

	private static String normalizeType(String type) {
		String value = eraseTypeArguments(type).replace(" ", "");
		int dimensions = 0;
		while (value.endsWith("[]")) {
			dimensions++;
			value = value.substring(0, value.length() - 2);
		}
		int dot = value.lastIndexOf('.');
		String simple = dot < 0 ? value : value.substring(dot + 1);
		return simple + "[]".repeat(dimensions);
	}

	private static String simpleType(String type) {
		String value = normalizeType(type);
		while (value.endsWith("[]")) {
			value = value.substring(0, value.length() - 2);
		}
		return value;
	}

	private static boolean unqualified(String type) {
		return !eraseTypeArguments(type).contains(".");
	}

	private static String eraseTypeArguments(String type) {
		StringBuilder result = new StringBuilder();
		int depth = 0;
		for (int index = 0; index < type.length(); index++) {
			char character = type.charAt(index);
			if (character == '<') {
				depth++;
			}
			else if (character == '>') {
				depth--;
			}
			else if (depth == 0) {
				result.append(character);
			}
		}
		return result.toString();
	}

}
