package ch.rasc.jrefine.tools.declarations;

import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.CallableDeclaration;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.ast.expr.AssignExpr;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.FieldAccessExpr;
import com.github.javaparser.ast.expr.LambdaExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.stmt.ReturnStmt;
import com.github.javaparser.ast.type.Type;
import ch.rasc.jrefine.analysis.TypeLookup;
import ch.rasc.jrefine.api.Finding;
import ch.rasc.jrefine.api.InspectionContext;
import ch.rasc.jrefine.api.PolicyInspectionTool;
import ch.rasc.jrefine.api.ToolResult;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/** Reports direct storage and return of mutable state across an object's API boundary. */
public final class ReportMutableStateExposureTool implements PolicyInspectionTool {

	private static final Set<String> JAVA_UTIL_MUTABLE_TYPES = Set.of("ArrayDeque", "ArrayList", "BitSet", "Calendar",
			"Collection", "Date", "Deque", "Dictionary", "HashMap", "HashSet", "Hashtable", "IdentityHashMap",
			"LinkedHashMap", "LinkedHashSet", "LinkedList", "List", "Map", "NavigableMap", "NavigableSet",
			"PriorityQueue", "Properties", "Queue", "Set", "SortedMap", "SortedSet", "Stack", "StringJoiner", "TreeMap",
			"TreeSet", "Vector", "WeakHashMap");

	private static final Set<String> ATOMIC_MUTABLE_TYPES = Set.of("AtomicBoolean", "AtomicInteger",
			"AtomicIntegerArray", "AtomicLong", "AtomicLongArray", "AtomicMarkableReference", "AtomicReference",
			"AtomicReferenceArray", "AtomicStampedReference", "DoubleAccumulator", "DoubleAdder", "LongAccumulator",
			"LongAdder");

	private static final Set<String> BUFFER_TYPES = Set.of("Buffer", "ByteBuffer", "CharBuffer", "DoubleBuffer",
			"FloatBuffer", "IntBuffer", "LongBuffer", "ShortBuffer");

	@Override
	public String id() {
		return "report-mutable-state-exposure";
	}

	@Override
	public String description() {
		return "Report mutable parameters stored directly in fields and mutable fields returned directly";
	}

	@Override
	public ToolResult inspect(InspectionContext context, boolean applyFixes) {
		if (generatedSource(context)) {
			return new ToolResult(List.of(), false);
		}
		ArrayList<Finding> findings = new ArrayList<>();
		for (ClassOrInterfaceDeclaration type : context.compilationUnit().findAll(ClassOrInterfaceDeclaration.class)) {
			if (type.isInterface()) {
				continue;
			}
			if (type.getAnnotations()
				.stream()
				.anyMatch(annotation -> Set.of("Entity", "Embeddable", "MappedSuperclass", "Document")
					.contains(annotation.getName().getIdentifier()))) {
				continue;
			}
			Map<String, VariableDeclarator> mutableFields = mutableFields(context, type);
			if (mutableFields.isEmpty()) {
				continue;
			}
			returnedFields(context, type, mutableFields, findings);
			storedParameters(context, type, mutableFields, findings);
		}
		return new ToolResult(List.copyOf(findings), false);
	}

	private static Map<String, VariableDeclarator> mutableFields(InspectionContext context,
			ClassOrInterfaceDeclaration type) {
		HashMap<String, VariableDeclarator> result = new HashMap<>();
		for (com.github.javaparser.ast.body.FieldDeclaration field : type.getFields()) {
			if (field.getAnnotations()
				.stream()
				.anyMatch(annotation -> Set.of("ElementCollection", "ManyToMany", "OneToMany")
					.contains(annotation.getName().getIdentifier()))) {
				continue;
			}
			field.getVariables()
				.stream()
				.filter(variable -> mutableType(context, variable.getType()))
				.forEach(variable -> result.put(variable.getNameAsString(), variable));
		}
		return result;
	}

	private static boolean generatedSource(InspectionContext context) {
		String source = context.editor().source();
		String prefix = source.substring(0, Math.min(source.length(), 1_000)).toLowerCase(java.util.Locale.ROOT);
		return prefix.contains("generated by") || context.compilationUnit()
			.getTypes()
			.stream()
			.flatMap(type -> type.getAnnotations().stream())
			.anyMatch(annotation -> annotation.getName().getIdentifier().equals("Generated")
					|| annotation.getName().getIdentifier().equals("SuppressWarnings")
							&& annotation.toString().contains("\"all\""));
	}

	private static void returnedFields(InspectionContext context, ClassOrInterfaceDeclaration type,
			Map<String, VariableDeclarator> fields, List<Finding> findings) {
		for (MethodDeclaration method : type.getMethods()) {
			if (method.isPrivate() || method.getBody().isEmpty()) {
				continue;
			}
			for (ReturnStmt returned : method.getBody().orElseThrow().findAll(ReturnStmt.class)) {
				if (!directlyWithin(returned, method)) {
					continue;
				}
				String name = fieldName(context, returned.getExpression().orElse(null), returned).orElse(null);
				if (name != null && fields.containsKey(name)) {
					findings.add(Finding.at(returned,
							"Mutable field '" + name + "' is returned directly; callers can modify internal state"));
				}
			}
		}
	}

	private static void storedParameters(InspectionContext context, ClassOrInterfaceDeclaration type,
			Map<String, VariableDeclarator> fields, List<Finding> findings) {
		ArrayList<CallableDeclaration<?>> callables = new ArrayList<>(type.getConstructors());
		callables.addAll(type.getMethods());
		for (CallableDeclaration<?> callable : callables) {
			Map<String, Parameter> parameters = callable.getParameters()
				.stream()
				.filter(parameter -> mutableType(context, parameterType(parameter)))
				.collect(java.util.stream.Collectors.toMap(Parameter::getNameAsString, parameter -> parameter));
			if (parameters.isEmpty()) {
				continue;
			}
			for (AssignExpr assignment : callable.findAll(AssignExpr.class)) {
				if (!directlyWithin(assignment, callable) || !(assignment.getValue() instanceof NameExpr value)
						|| !parameters.containsKey(value.getNameAsString())) {
					continue;
				}
				String target = fieldName(context, assignment.getTarget(), assignment).orElse(null);
				if (target != null && fields.containsKey(target)) {
					findings.add(Finding.at(assignment, "Mutable parameter '" + value.getNameAsString()
							+ "' is stored directly in field '" + target + "'; retain a defensive copy instead"));
				}
			}
		}
	}

	private static Type parameterType(Parameter parameter) {
		if (!parameter.isVarArgs()) {
			return parameter.getType();
		}
		return new com.github.javaparser.ast.type.ArrayType(parameter.getType().clone());
	}

	private static Optional<String> fieldName(InspectionContext context, Expression expression, Node use) {
		if (expression instanceof FieldAccessExpr access && access.getScope().isThisExpr()) {
			return Optional.of(access.getNameAsString());
		}
		if (!(expression instanceof NameExpr name)
				|| TypeLookup.isVisibleLocalOrParameter(context.compilationUnit(), name.getNameAsString(), use)) {
			return Optional.empty();
		}
		return Optional.of(name.getNameAsString());
	}

	private static boolean mutableType(InspectionContext context, Type type) {
		if (type.isArrayType()) {
			return true;
		}
		String spelling = type.asString();
		return TypeLookup.isKnownJavaLangType(context.compilationUnit(), spelling,
				Set.of("StringBuffer", "StringBuilder"))
				|| TypeLookup.isKnownJavaUtilType(context.compilationUnit(), spelling, JAVA_UTIL_MUTABLE_TYPES)
				|| TypeLookup.isKnownType(context.compilationUnit(), spelling, "java.util.concurrent.atomic",
						ATOMIC_MUTABLE_TYPES)
				|| TypeLookup.isKnownType(context.compilationUnit(), spelling, "java.nio", BUFFER_TYPES);
	}

	private static boolean directlyWithin(Node node, CallableDeclaration<?> callable) {
		Optional<Node> current = node.getParentNode();
		while (current.isPresent()) {
			Node parent = current.orElseThrow();
			if (parent == callable) {
				return true;
			}
			if (parent instanceof CallableDeclaration<?> || parent instanceof LambdaExpr) {
				return false;
			}
			current = parent.getParentNode();
		}
		return false;
	}

}
