package ch.rasc.jrefine.tools.declarations;

import com.github.javaparser.ast.Modifier;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.AnnotationDeclaration;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.ast.expr.FieldAccessExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.nodeTypes.NodeWithModifiers;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import com.github.javaparser.ast.type.Type;
import ch.rasc.jrefine.analysis.AstSupport;
import ch.rasc.jrefine.analysis.TypeLookup;
import ch.rasc.jrefine.api.Finding;
import ch.rasc.jrefine.api.InspectionContext;
import ch.rasc.jrefine.api.PolicyInspectionTool;
import ch.rasc.jrefine.api.ToolResult;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Reports source-local visibility choices that widen or bypass encapsulation boundaries.
 */
public final class ReportEncapsulationPolicyIssuesTool implements PolicyInspectionTool {

	@Override
	public String id() {
		return "report-encapsulation-policy-issues";
	}

	@Override
	public String description() {
		return "Report exposed fields and nested types, cross-object field access, and visibility leaks";
	}

	@Override
	public ToolResult inspect(InspectionContext context, boolean applyFixes) {
		if (generatedSource(context)) {
			return new ToolResult(List.of(), false);
		}
		ArrayList<Finding> findings = new ArrayList<>();
		fieldVisibility(context, findings);
		nestedTypeVisibility(context, findings);
		crossObjectFieldAccess(context, findings);
		publicConstructors(context, findings);
		exposedTypes(context, findings);
		return new ToolResult(List.copyOf(findings), false);
	}

	private static void fieldVisibility(InspectionContext context, List<Finding> findings) {
		for (FieldDeclaration field : context.compilationUnit().findAll(FieldDeclaration.class)) {
			TypeDeclaration<?> owner = field.getParentNode()
				.filter(TypeDeclaration.class::isInstance)
				.map(TypeDeclaration.class::cast)
				.orElse(null);
			if (owner == null || implicitPublicMembers(owner) || field.isPrivate() || constant(field)
					|| !field.getAnnotations().isEmpty()) {
				continue;
			}
			String visibility;
			if (field.isPublic()) {
				visibility = "Public";
			}
			else if (field.isProtected()) {
				visibility = "Protected";
			}
			else {
				visibility = "Package-visible";
			}
			for (VariableDeclarator variable : field.getVariables()) {
				findings.add(Finding.at(variable,
						visibility + " field '" + variable.getNameAsString() + "' exposes representation state"));
			}
		}
	}

	private static boolean constant(FieldDeclaration field) {
		return field.isStatic() && field.isFinal();
	}

	private static boolean generatedSource(InspectionContext context) {
		String source = context.editor().source();
		String prefix = source.substring(0, Math.min(source.length(), 1_000)).toLowerCase(java.util.Locale.ROOT);
		return prefix.contains("generated by") || context.compilationUnit()
			.getTypes()
			.stream()
			.flatMap(type -> type.getAnnotations().stream())
			.anyMatch(annotation -> annotation.getName().getIdentifier().equals("Generated")
					|| annotation.getName().getIdentifier().equals("SuppressWarnings")
							&& annotation.toString().contains("\"all\""));
	}

	private static void nestedTypeVisibility(InspectionContext context, List<Finding> findings) {
		for (TypeDeclaration<?> nested : context.compilationUnit().findAll(TypeDeclaration.class)) {
			if (!(nested instanceof ClassOrInterfaceDeclaration declaration) || declaration.isInterface()) {
				continue;
			}
			TypeDeclaration<?> owner = nested.getParentNode()
				.filter(TypeDeclaration.class::isInstance)
				.map(TypeDeclaration.class::cast)
				.orElse(null);
			if (owner == null || implicitPublicMembers(owner) || nested.isPrivate()) {
				continue;
			}
			String visibility;
			if (nested.isPublic()) {
				visibility = "Public";
			}
			else if (nested.isProtected()) {
				visibility = "Protected";
			}
			else {
				visibility = "Package-visible";
			}
			findings.add(Finding.at(nested,
					visibility + " nested type '" + nested.getNameAsString() + "' broadens the enclosing API surface"));
		}
	}

	private static boolean implicitPublicMembers(TypeDeclaration<?> owner) {
		return owner instanceof ClassOrInterfaceDeclaration declaration && declaration.isInterface()
				|| owner instanceof AnnotationDeclaration;
	}

	private static void crossObjectFieldAccess(InspectionContext context, List<Finding> findings) {
		Map<String, ClassOrInterfaceDeclaration> types = uniqueClasses(context);
		for (FieldAccessExpr access : context.compilationUnit().findAll(FieldAccessExpr.class)) {
			if (!(access.getScope() instanceof NameExpr scope)) {
				continue;
			}
			String spelling = TypeLookup.visibleType(context.compilationUnit(), scope, access).orElse(null);
			ClassOrInterfaceDeclaration owner = sourceClass(spelling, types);
			if (owner == null || AstSupport.ancestor(access, ClassOrInterfaceDeclaration.class)
				.filter(current -> current == owner)
				.isEmpty()) {
				continue;
			}
			FieldDeclaration field = owner.getFields()
				.stream()
				.filter(candidate -> !candidate.isStatic() && !candidate.isPublic())
				.filter(candidate -> candidate.getVariables()
					.stream()
					.anyMatch(variable -> variable.getNameAsString().equals(access.getNameAsString())))
				.findFirst()
				.orElse(null);
			if (field != null) {
				findings.add(Finding.at(access,
						"Non-public field '" + access.getNameAsString() + "' is accessed through another object"));
			}
		}
	}

	private static void publicConstructors(InspectionContext context, List<Finding> findings) {
		for (ClassOrInterfaceDeclaration type : context.compilationUnit().findAll(ClassOrInterfaceDeclaration.class)) {
			if (type.isInterface() || effectiveVisibility(type) == Visibility.PUBLIC) {
				continue;
			}
			type.getConstructors()
				.stream()
				.filter(ConstructorDeclaration::isPublic)
				.forEach(constructor -> findings
					.add(Finding.at(constructor, "Public constructor belongs to a non-public class")));
		}
	}

	private static void exposedTypes(InspectionContext context, List<Finding> findings) {
		Map<String, TypeDeclaration<?>> types = uniqueTypes(context);
		for (TypeDeclaration<?> owner : context.compilationUnit().findAll(TypeDeclaration.class)) {
			int ownerVisibility = effectiveVisibility(owner).rank;
			if (ownerVisibility == Visibility.PRIVATE.rank) {
				continue;
			}
			if (owner instanceof ClassOrInterfaceDeclaration declaration) {
				for (ClassOrInterfaceType parent : declaration.getExtendedTypes()) {
					reportExposure(parent, ownerVisibility, types, findings, declaration);
				}
				for (ClassOrInterfaceType parent : declaration.getImplementedTypes()) {
					reportExposure(parent, ownerVisibility, types, findings, declaration);
				}
			}
			for (BodyDeclaration<?> member : owner.getMembers()) {
				int apiVisibility = Math.min(ownerVisibility, memberVisibility(owner, member).rank);
				if (apiVisibility <= Visibility.PRIVATE.rank) {
					continue;
				}
				if (member instanceof FieldDeclaration field) {
					reportExposure(field.getElementType(), apiVisibility, types, findings, field);
				}
				else if (member instanceof MethodDeclaration method) {
					reportExposure(method.getType(), apiVisibility, types, findings, method);
					method.getParameters()
						.forEach(parameter -> reportExposure(parameter.getType(), apiVisibility, types, findings,
								method));
					method.getThrownExceptions()
						.forEach(exception -> reportExposure(exception, apiVisibility, types, findings, method));
				}
				else if (member instanceof ConstructorDeclaration constructor) {
					constructor.getParameters()
						.forEach(parameter -> reportExposure(parameter.getType(), apiVisibility, types, findings,
								constructor));
					constructor.getThrownExceptions()
						.forEach(exception -> reportExposure(exception, apiVisibility, types, findings, constructor));
				}
			}
		}
	}

	private static void reportExposure(Type type, int apiVisibility, Map<String, TypeDeclaration<?>> types,
			List<Finding> findings, Node declaration) {
		HashSet<String> reported = new HashSet<>();
		for (ClassOrInterfaceType reference : referencedTypes(type)) {
			TypeDeclaration<?> exposed = sourceType(reference.asString(), types);
			if (exposed != null && effectiveVisibility(exposed).rank < apiVisibility
					&& reported.add(exposed.getNameAsString())) {
				findings
					.add(Finding.at(declaration, "API exposes less-visible type '" + exposed.getNameAsString() + "'"));
			}
		}
	}

	private static List<ClassOrInterfaceType> referencedTypes(Type type) {
		ArrayList<ClassOrInterfaceType> result = new ArrayList<>();
		if (type instanceof ClassOrInterfaceType reference) {
			result.add(reference);
		}
		for (ClassOrInterfaceType reference : type.findAll(ClassOrInterfaceType.class)) {
			if (!result.contains(reference)) {
				result.add(reference);
			}
		}
		return result;
	}

	private static Visibility effectiveVisibility(TypeDeclaration<?> type) {
		Visibility result = declaredVisibility(type);
		Optional<TypeDeclaration> current = AstSupport.ancestor(type, TypeDeclaration.class)
			.map(value -> (TypeDeclaration) value);
		while (current.isPresent()) {
			Visibility outer = declaredVisibility(current.orElseThrow());
			if (outer.rank < result.rank) {
				result = outer;
			}
			current = AstSupport.ancestor(current.orElseThrow(), TypeDeclaration.class)
				.map(value -> (TypeDeclaration) value);
		}
		return result;
	}

	private static Visibility memberVisibility(TypeDeclaration<?> owner, BodyDeclaration<?> member) {
		if (!(member instanceof NodeWithModifiers<?> modifiers)) {
			return Visibility.PRIVATE;
		}
		if (modifiers.hasModifier(Modifier.Keyword.PUBLIC)) {
			return Visibility.PUBLIC;
		}
		if (modifiers.hasModifier(Modifier.Keyword.PROTECTED)) {
			return Visibility.PROTECTED;
		}
		if (modifiers.hasModifier(Modifier.Keyword.PRIVATE)) {
			return Visibility.PRIVATE;
		}
		if (implicitPublicMembers(owner)) {
			return Visibility.PUBLIC;
		}
		return Visibility.PACKAGE;
	}

	private static Visibility declaredVisibility(TypeDeclaration<?> type) {
		if (type.isPublic()) {
			return Visibility.PUBLIC;
		}
		if (type.isProtected()) {
			return Visibility.PROTECTED;
		}
		if (type.isPrivate()) {
			return Visibility.PRIVATE;
		}
		if (type.getParentNode()
			.filter(TypeDeclaration.class::isInstance)
			.map(TypeDeclaration.class::cast)
			.filter(ReportEncapsulationPolicyIssuesTool::implicitPublicMembers)
			.isPresent()) {
			return Visibility.PUBLIC;
		}
		return Visibility.PACKAGE;
	}

	private static Map<String, ClassOrInterfaceDeclaration> uniqueClasses(InspectionContext context) {
		HashMap<String, List<ClassOrInterfaceDeclaration>> grouped = new HashMap<>();
		context.compilationUnit()
			.findAll(ClassOrInterfaceDeclaration.class)
			.forEach(type -> grouped.computeIfAbsent(type.getNameAsString(), ignored -> new ArrayList<>()).add(type));
		HashMap<String, ClassOrInterfaceDeclaration> result = new HashMap<>();
		grouped.forEach((name, declarations) -> {
			if (declarations.size() == 1) {
				result.put(name, declarations.getFirst());
			}
		});
		return result;
	}

	private static Map<String, TypeDeclaration<?>> uniqueTypes(InspectionContext context) {
		HashMap<String, List<TypeDeclaration<?>>> grouped = new HashMap<>();
		context.compilationUnit()
			.findAll(TypeDeclaration.class)
			.forEach(type -> grouped.computeIfAbsent(type.getNameAsString(), ignored -> new ArrayList<>()).add(type));
		HashMap<String, TypeDeclaration<?>> result = new HashMap<>();
		grouped.forEach((name, declarations) -> {
			if (declarations.size() == 1) {
				result.put(name, declarations.getFirst());
			}
		});
		return result;
	}

	private static ClassOrInterfaceDeclaration sourceClass(String spelling,
			Map<String, ClassOrInterfaceDeclaration> types) {
		if (spelling == null || !unqualified(spelling)) {
			return null;
		}
		return types.get(simpleType(spelling));
	}

	private static TypeDeclaration<?> sourceType(String spelling, Map<String, TypeDeclaration<?>> types) {
		if (!unqualified(spelling)) {
			return null;
		}
		return types.get(simpleType(spelling));
	}

	private static boolean unqualified(String type) {
		String value = eraseTypeArguments(type);
		return !value.contains(".");
	}

	private static String simpleType(String type) {
		String value = eraseTypeArguments(type);
		while (value.endsWith("[]")) {
			value = value.substring(0, value.length() - 2);
		}
		int dot = value.lastIndexOf('.');
		return dot < 0 ? value : value.substring(dot + 1);
	}

	private static String eraseTypeArguments(String type) {
		StringBuilder result = new StringBuilder();
		int depth = 0;
		for (int index = 0; index < type.length(); index++) {
			char character = type.charAt(index);
			if (character == '<') {
				depth++;
			}
			else if (character == '>') {
				depth--;
			}
			else if (depth == 0) {
				result.append(character);
			}
		}
		return result.toString().replace(" ", "");
	}

	private enum Visibility {

		PRIVATE(0), PACKAGE(1), PROTECTED(2), PUBLIC(3);

		private final int rank;

		Visibility(int rank) {
			this.rank = rank;
		}

	}

}
