package ch.rasc.jrefine.tools.declarations;

import ch.rasc.jrefine.TestSources;
import ch.rasc.jrefine.api.InspectionContext;
import ch.rasc.jrefine.api.InspectionTool;
import ch.rasc.jrefine.api.ToolResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LanguageAndModuleContractToolsTest {

	@Test
	void reportsSourceLocalApiNamingAndOverloadConflicts() {
		ToolResult result = inspect(new ReportApiNamingConflictsTool(), """
				import java.util.function.Consumer;
				import java.util.function.Function;
				interface Contract { void load(String path); }
				class Parent {
				    void inherited(String name) {}
				    void trace(Object... values) {}
				}
				class Sample extends Parent implements Contract {
				    public void load(String value) {}
				    @Override void inherited(String value) {}
				    void Sample() {}
				    void Parent() {}
				    void read() {}
				    void Read() {}
				    void send(String text) {}
				    void send(int code) {}
				    void transform(Consumer<String> consumer) {}
				    void transform(Function<String, String> function) {}
				    void trace(String label, Object... values) {}
				}
				class Same extends other.Same {}
				""");

		assertMessages(result, "differs from overridden", "same name as an ancestor",
				"same name as its containing class", "same name as parent class", "differ only by case",
				"same number of parameters", "conflicting functional-interface", "Varargs method is overloaded");
	}

	@Test
	void acceptsConsistentAndNonConflictingApis() {
		ToolResult result = inspect(new ReportApiNamingConflictsTool(), """
				interface Contract { void load(String path); }
				class Parent { void inherited(String name) {} }
				class Sample extends Parent implements Contract {
				    public void load(String path) {}
				    @Override void inherited(String name) {}
				    void parse() {}
				    void parse(String input) {}
				    void log(String... values) {}
				}
				""");

		assertTrue(result.findings().isEmpty(), result.findings().toString());

		ToolResult generated = inspect(new ReportApiNamingConflictsTool(), """
				// Generated by API compiler
				class Generated { void Generated() {} void read() {} void Read() {} }
				""");
		assertTrue(generated.findings().isEmpty(), generated.findings().toString());
	}

	@Test
	void reportsEmptyAndSelfTargetedModuleDirectives() {
		ToolResult empty = inspect(new ReportModuleContractIssuesTool(), "module sample.empty {}");
		assertMessages(empty, "Empty module-info.java");

		ToolResult selfTargeted = inspect(new ReportModuleContractIssuesTool(), """
				module sample.app {
				    exports sample.api to sample.app;
				    opens sample.internal to sample.app;
				}
				""");
		assertMessages(selfTargeted, "exports a package to itself", "opens a package to itself");

		ToolResult valid = inspect(new ReportModuleContractIssuesTool(), """
				module sample.app {
				    requires java.sql;
				    exports sample.api to sample.consumer;
				}
				""");
		assertTrue(valid.findings().isEmpty(), valid.findings().toString());
	}

	@Test
	void reportsServiceLoaderUseMissingFromNearestModule(@TempDir Path directory) throws IOException {
		Path descriptor = directory.resolve("module-info.java");
		Files.writeString(descriptor, "module sample.app { exports sample; }");
		Path sourcePath = directory.resolve("sample").resolve("App.java");

		String source = """
				package sample;
				import java.util.ServiceLoader;
				import sample.spi.PaymentService;
				class App {
				    void start() { ServiceLoader.load(PaymentService.class); }
				}
				""";
		ToolResult missing = inspect(new ReportModuleContractIssuesTool(), sourcePath, source);
		assertMessages(missing, "sample.spi.PaymentService", "not declared with uses");

		Files.writeString(descriptor, """
				module sample.app {
				    exports sample;
				    uses sample.spi.PaymentService;
				}
				""");
		ToolResult declared = inspect(new ReportModuleContractIssuesTool(), sourcePath, source);
		assertTrue(declared.findings().isEmpty(), declared.findings().toString());
	}

	private static ToolResult inspect(InspectionTool tool, String source) {
		return inspect(tool, TestSources.parse(source));
	}

	private static ToolResult inspect(InspectionTool tool, Path path, String source) {
		InspectionContext parsed = TestSources.parse(source);
		return inspect(tool, new InspectionContext(path, parsed.compilationUnit(), source));
	}

	private static ToolResult inspect(InspectionTool tool, InspectionContext context) {
		ToolResult result = tool.inspect(context, true);
		assertFalse(result.changed(), "Reporter must not change source");
		return result;
	}

	private static List<String> messages(ToolResult result) {
		return result.findings().stream().map(finding -> finding.message()).toList();
	}

	private static void assertMessages(ToolResult result, String... fragments) {
		List<String> messages = messages(result);
		for (String fragment : fragments) {
			assertTrue(messages.stream().anyMatch(message -> message.contains(fragment)),
					() -> "Missing '" + fragment + "' in " + messages);
		}
	}

}
